# Generated by Django 4.0.2 on 2022-02-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='submission_date',
            field=models.DateField(verbose_name='Дата сдачи'),
        ),
    ]
