# Generated by Django 4.0.2 on 2022-02-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_meter_submission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='reading',
        ),
        migrations.AlterField(
            model_name='meter',
            name='submission_date',
            field=models.DateField(verbose_name='Следующая дата сдачи'),
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(verbose_name='Дата сдачи')),
                ('value', models.PositiveIntegerField(verbose_name='Показание')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_reading', to='payment.meter', verbose_name='Счетчик')),
            ],
            options={
                'verbose_name': 'Показание',
                'verbose_name_plural': 'Показания',
                'ordering': ['created'],
            },
        ),
    ]
