# Generated by Django 4.0.2 on 2022-02-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_meter_reading_alter_meter_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading', to='payment.meter', verbose_name='Счетчик'),
        ),
    ]
