# Generated by Django 4.0.2 on 2022-02-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_reading_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата сдачи'),
        ),
    ]
