# Generated by Django 4.0.2 on 2022-02-21 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_reading_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meter',
            options={'ordering': ['owner'], 'verbose_name': 'Счетчик', 'verbose_name_plural': 'Счетчики'},
        ),
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['-date'], 'verbose_name': 'Показание', 'verbose_name_plural': 'Показания'},
        ),
        migrations.RemoveField(
            model_name='meter',
            name='status',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='created',
        ),
        migrations.AddField(
            model_name='reading',
            name='date',
            field=models.DateField(default=datetime.date(2022, 2, 21), verbose_name='Дата сдачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('undone', 'undone')], default='UNDONE', max_length=8, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
