# Generated by Django 4.0.2 on 2022-02-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_meter_options_alter_reading_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Показание'),
        ),
    ]
