# Generated by Django 3.2.9 on 2021-12-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_task_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.task', verbose_name='Задание'),
        ),
    ]
