# Generated by Django 3.2.9 on 2021-12-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_offer_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='freelancer',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='customer',
            new_name='author',
        ),
    ]
