POST http://0.0.0.0:8080/auth/sign-in
Content-Type: application/json

{
  "login": "yana",
  "psw": "1234"
}

###

POST http://0.0.0.0:8080/auth/sign-up
Content-Type: application/json

{
  "login": "yana2",
  "psw": "123456"
}

###

POST http://0.0.0.0:8080/auth/sign-in
Content-Type: application/json

{
  "login": "yana1",
  "psw": "123456"
}

###

GET http://0.0.0.0:8080/forum/request/hierarchy
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsInBzdyI6IjEyMzQiLCJpc3MiOiJ5YW5hIiwibG9naW4iOiJ5YW5hIn0.hx0WNc-_Sx7Eu2CijBhni-KMEaMVQ9fntS_UHzNxx74

###

GET http://0.0.0.0:8080/forum/request/active-users
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsInBzdyI6IjEyMzQiLCJpc3MiOiJ5YW5hIiwibG9naW4iOiJ5YW5hIn0.hx0WNc-_Sx7Eu2CijBhni-KMEaMVQ9fntS_UHzNxx74

###

GET http://0.0.0.0:8080/forum/request/message
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsInBzdyI6IjEyMzQiLCJpc3MiOiJ5YW5hIiwibG9naW4iOiJ5YW5hIn0.hx0WNc-_Sx7Eu2CijBhni-KMEaMVQ9fntS_UHzNxx74

{
  "subTheme": "qerv",
  "msg": "ehnethn"
}

###

GET http://0.0.0.0:8080/forum/request/message-list
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsInBzdyI6IjEyMzQiLCJpc3MiOiJ5YW5hIiwibG9naW4iOiJ5YW5hIn0.hx0WNc-_Sx7Eu2CijBhni-KMEaMVQ9fntS_UHzNxx74

{
  "subTheme": "qerv"
}

###

DELETE http://0.0.0.0:8080/forum/request/logout
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsInBzdyI6IjEyMzQiLCJpc3MiOiJ5YW5hIiwibG9naW4iOiJ5YW5hIn0.hx0WNc-_Sx7Eu2CijBhni-KMEaMVQ9fntS_UHzNxx74